# Generated by Django 4.1.7 on 2023-03-20 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_productattribute_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='image',
            field=models.ImageField(upload_to='product_imgs/'),
        ),
    ]
