# Generated by Django 4.1.7 on 2023-04-20 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_cartorder_address_cartorder_email_cartorder_mobile_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Banner',
        ),
    ]
